export const services = [
  { id: "monitoring", cat: "Security Operations", title: "Security Monitoring & Alert Workflows", blurb: "Turn the alerts you already get into an owned, tracked, reported process.", items: ["Security Monitoring QuickStart", "Wazuh / Open-Source SOC Setup", "Microsoft 365 Security Workflow Setup", "Alert-to-Ticket Automation", "Monthly Workflow Support"] },
  { id: "ai-soc", cat: "Security Operations", flag: true, title: "AI-Assisted SOC", blurb: "AI-assisted triage and recommendations — with your team approving every action.", items: ["AI SOC Workflow Pilot", "MSP Security Workflow Enablement", "24/7 Monitoring (Analyst-Staffed)"], note: "24/7 coverage is scoped per engagement." },
  { id: "vuln-pentest", cat: "Vulnerability & Testing", title: "Vulnerability Assessment & Penetration Testing", blurb: "Find what attackers would — across infrastructure, apps, and cloud.", items: ["Infrastructure Vulnerability Assessment", "Web Application Vulnerability Assessment", "Cloud Security Assessment", "Network Penetration Test", "Web Application Penetration Test", "Security Configuration / Hardening Review"], note: "Testing is delivered under written client authorization, scoped per engagement." },
  { id: "compliance", cat: "GRC & Compliance", title: "Compliance Readiness", blurb: "Get ready for the audit, whatever framework applies.", items: ["Compliance Readiness Advisory (any framework)", "Compliance Evidence Automation"], note: "CaiberOne is not a certification body or auditor. We do not certify compliance or guarantee audit outcomes. We support readiness by implementing the technical controls, workflows, and evidence processes your auditor will assess." },
  { id: "risk-governance", cat: "GRC & Compliance", title: "Risk & Governance", blurb: "Know your gaps and put the right policies and controls in place.", items: ["Risk Assessment & Gap Analysis", "Security Policy & Procedure Pack"] },
  { id: "advisory", cat: "GRC & Compliance", title: "Security Advisory", blurb: "Senior security guidance when you need direction, not just execution.", items: ["Security architecture review", "Advisory / vCISO-style guidance (scoped per engagement)"] },
];
export const integrations = ["Wazuh","Microsoft Defender","CrowdStrike","Splunk","Elastic SIEM","Jira","Slack","PagerDuty","ServiceNow","Suricata","TheHive","MISP","Shuffle","IBM QRadar","Kaspersky","Velociraptor","Thor","Redline","AWS","Microsoft Azure"];
export const industries = [["MSPs","Repeatable workflows you can run across every client tenancy."],["SaaS & tech startups","Security operations that scale with you as headcount and surface area grow."],["Regulated SMBs","Practical controls sized to a lean team, not an enterprise budget."],["Healthcare","Monitoring and compliance readiness built around patient-data obligations."],["GCC compliance-driven organizations","Regional frameworks — SAMA CSF, NCNICC-1:2025, ECC-2:2024 — implemented alongside your own."]];
export const trust = [["You own what we build","Every runbook, configuration, and decision log — yours to keep."],["You approve every action","AI does the heavy lifting; your team stays in control of every response action."],["Runs in your environment","On your tenancy, on your tooling — not ours."],["Fixed scope, documented handover","A defined start and end, agreed before work begins."]];
export const principles = [["Practical first","We focus on outcomes, not theoretical frameworks. Every engagement produces working security processes your team can operate on day one — no lengthy implementation cycles, no hidden dependencies."],["Human-controlled AI","AI handles the volume; humans make the decisions. Every automated action is visible, auditable, and subject to analyst review. No black-box responses, no actions without an owner."],["Works with your stack","We integrate with the tools you already use. No rip-and-replace, no new consoles to learn, no pressure to adopt a proprietary ecosystem. Your investment stays yours."]];
export const regions = [["North America","United States","Supporting US-based clients across compliance-sensitive industries — finance, healthcare, SaaS, and government contracting."],["Gulf Region","GCC","Serving clients across the Gulf Cooperation Council with regional regulatory knowledge and on-the-ground availability."],["European Operations","Europe","Helping European organisations navigate GDPR, NIS2, and sector-specific requirements with practical, audit-ready security programs."]];
export const faqs = [["Who do you work with?","Startups, SMBs, MSPs, and lean IT/security teams that need practical security operations without enterprise overhead."],["Do you offer 24/7 monitoring?","Yes, as analyst-staffed 24/7 monitoring under AI-Assisted SOC. Coverage is scoped per engagement."],["Will you certify us for compliance?","No. CaiberOne is not a certification body or auditor. We implement the technical controls, workflows, and evidence processes your auditor will assess."],["Who approves AI-driven actions?","Your team. AI handles triage and recommendations; every response action is visible, auditable, and approved by a person."],["Do we need to replace our tools?","No. We integrate with the tools you already run, on your tenancy, with no rip-and-replace."],["Is penetration testing authorized?","Always. Testing is delivered under written client authorization and scoped per engagement."],["What do we keep at the end?","Everything: every runbook, configuration, and decision log, plus a documented handover."]];

export const alertQueue = [["INC-4417", "CRITICAL", "prod-eu-04", "14:02:11"], ["INC-4416", "HIGH", "vpn-gw-02", "13:48:02"], ["INC-4415", "ELEVATED", "sso.caiberone", "12:11:57"], ["INC-4412", "CLEAR", "build-agent-9", "09:41:30"]];
export const workflowSteps = [
  ["Alert", "A detection fires from the tools you already run."],
  ["Normalize", "The raw event is parsed into a consistent, comparable record."],
  ["Enrich", "Asset, identity, and threat-intel context is attached."],
  ["AI-assisted summary", "AI drafts what happened and why it matters, in plain language.", true],
  ["Prioritize", "Ranked against your own asset criticality, not a generic score."],
  ["Notify", "Your team is pinged in Slack or Teams — not buried in an inbox."],
  ["Ticket", "A ticket opens in Jira, ServiceNow, or TheHive with context attached."],
  ["Human approval", "A person reviews and approves before any response action runs."],
  ["Report", "The outcome is documented and written back to the record."],
];
